SPOOL SQL_VERIFY_LOG.log;
SET HEADING OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE

DECLARE
    OUTCOME VARCHAR(255);
BEGIN
    OUTCOME := SR_DUMMY_PKG.DUMMY_PROCEDURE;

    IF(OUTCOME <> 'ALIVE')
        THEN
            DBMS_OUTPUT.PUT_LINE('___ERROR___');
        ELSE
            DBMS_OUTPUT.PUT_LINE('___OK___');
    END IF;
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('___ERROR___');
END;
/
SPOOL OFF;
EXIT;
