SPOOL SQL_VERIFY_LOG.log;
SET HEADING OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE

DECLARE
    OUTCOME VARCHAR(255);
BEGIN
    OUTCOME := SR_DUMMY_PKG.DUMMY_PROCEDURE;

    IF(OUTCOME = 'ALIVE') THEN
      DBMS_OUTPUT.PUT_LINE('@SUCCESS');
    END IF;
END;
/
SPOOL OFF;
EXIT;
