SPOOL SQL_DEPLOY_LOG.log
SET FEEDBACK ON
SET HEADING OFF
SET VERIFY OFF
SET PAGESIZE 0
SET TERMOUT OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT FAILURE

@./CREATE_SR_DUMMY_PKG_SPEC.sql
@./CREATE_SR_DUMMY_PKG_BODY.sql

BEGIN
  DBMS_OUTPUT.PUT_LINE('@SUCCESS');
END;
/

SPOOL OFF;
EXIT;
